version: '3.7'
services:
  mysql-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql # MySQL data files
      - ./mysql/configs:/etc/mysql/config.d # MySQL config files
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: ${APP_DBNAME}
      MYSQL_USER: ${APP_DBUSER}
      MYSQL_PASSWORD: ${APP_DBPASS}
      TZ: Europe/Kiev
    ports:
      - 6036:3306

  nginx:
    image: jsnow0177/nginx-vim:1.0
    restart: always
    volumes:
      - ./nginx/logs:/var/log/nginx # Nginx logs
      - ./nginx/configs/conf.d:/etc/nginx/conf.d
      - ./nginx/configs/nginx.conf:/etc/nginx/nginx.conf # Main nginx configuration file
      - ./web:/var/www/webdata
    environment:
      TZ: Europe/Kiev
    ports:
      - ${WEBSERVER_PORT}:8080
    links:
      - php-fpm
    working_dir: /var/www/webdata
    hostname: todoapp

  php-fpm:
    restart: always
    build: ./php-fpm
    volumes:
      - ./web:/var/www/webdata
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      TZ: Europe/Kiev
      PHINX_DBHOST: ${APP_DBHOST} # Environment variables for Phinx
      PHINX_DBNAME: ${APP_DBNAME}
      PHINX_DBUSER: ${APP_DBUSER}
      PHINX_DBPASS: ${APP_DBPASS}
    working_dir: /var/www/webdata
    hostname: todoapp
    links:
      - mysql-server